### ISSUE TITLE
soap:Fault not recognized as fault

### ISSUE THREAD

**Issue by winsmith** [jkichline/sudzc#3]
I'm trying to catch a SoapFault returned by my server, but it isn't recognized as such. Instead, it returns a result of nil.

I'm getting this xml back from the server:

```
<CXMLDocument 0x6b60210 [0x688fc40]> <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <soap:Fault>
            <faultcode>soap:Client</faultcode>
            <faultstring>System.Web.Services.Protocols.SoapException: joynerror,Security,100,"Access denied"
               at Joyn.WebServices.AccountServices.Login(String userName, String password, Boolean createPersistantCookie)</faultstring>
            <faultactor>cosevenFault</faultactor>
            <detail>
                <errorNamespace>Security</errorNamespace>
                <errorCode>100</errorCode>
                <errorMessage>joynerror,Security,100,"Access denied"</errorMessage>
                <errorDetails/>
            </detail>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>
```

It gets passed into SoapFault::faultWithXMLDocument: which tries to get the fault's XML element with `[Soap getNode: [document rootElement] withName: @"Fault"]`. This doesn't work though, since "soap:Fault" doesn't get recognized as the same as "Fault". 

How can I work around this? Can I add a namespace somehow? My code works if I change line 26 in SoapFault.m to `return [SoapFault faultWithXMLElement: [Soap getNode: [document rootElement] withName: @"soap:Fault"]];`, but it seems hacky, and I'm afraid I might break something.

**Comment by GevaZeichner** [comment]
I've encountered this too with soap:Body.
To fix this, in getNode:withName: I've replaced [child name] with [child localName].
